server:
  port: 36036
  servlet:
    context-path: /web
  tomcat:
    uri-encoding: UTF-8
# 以上的配置组成了完整的路径： localhost:36036/web/*

spring:
  datasource:
    url: jdbc:mysql://182.92.196.182:36006/ReView?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Sense1236
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1

  http:
    #解决中文乱码问题
    encoding:
      force: true
      enabled: true
      charset: UTF-8
mybatis:
  mapperLocations: classpath:/mapper/*.xml
  type-aliases-package: com.ryan.review.model



